### ISSUE TITLE
عدم آپلود سایت

### ISSUE THREAD

**Issue by kanganpishgaman** [certifiedtruecopy/C2C_SSH#5]
با سلام استاد گرامی
در نسخه جدید که روی گزینه upload web site که می زنیم سایت را که اضافه می نماییم همش صفحه ngnix باز می شود با نسخه قدیمی درجا سایت اپلود شد و سایت باز کرد و در گرفتن certificat خیلی دیر انجام می دهد 
اگر می شود یک بررسی شود ببینید مشکل از کجاست

**Comment by certifiedtruecopy** [comment]
سلام دوست عزیز این مشکل در نسخه جدید بر طرف شد
