### ISSUE TITLE
اضافه کردن سرور

### ISSUE THREAD

**Issue by kanganpishgaman** [certifiedtruecopy/C2C_SSH#6]
با سلام بر استاد گرامی 
می شود کاری کنید یک گزینه به نام add server اضافه نمایید
به این صورت که مثلا من دو تا سرور دارم اینها در گزینهadd server  ذخیره می نمایم هر زمان که نیاز داشتم با کلیلک بر روی آن سرور کل اطلاعات شامل پورت و یوزر و پسورد آن به صورت اتوماتیک بالا می اید و دیگر نیاز به تایپ اطلاعات سرور نباشد مثل نرم افزار winbox برای سیستم عامل های میکروتیک استفاده می شود

**Comment by certifiedtruecopy** [comment]
سلام دوست من بله امکان پذیر هست ولی به دلایل امنیت سرور این کار رو انجام ندادم که هیچ اصلاعاتی هیچ جا ثبت و ذخیره نشود
