### ISSUE TITLE
کادر برنامه

### ISSUE THREAD

**Issue by miladia13** [certifiedtruecopy/C2C_SSH#8]
سلام آرش جان خسته نباشید یه مشکلی دارم وقتی اد یوزر میزنم بعد از اینکه یوزر رو با truecopy ساختم :) کارد پسورد میپره پشت کادر اپ دوباره باید کادر برنامه رو مینی مایز کنیم یا ببریم پایین تا بتونیم تاریخ و حجم رو وارد کنیم خلاصه اینکه کادرش مخفی میشه زیر کادر اصلی دومین مشکل کرش کردن اپ در وینودوز 10 سیستم قدیمیه مپلا سی پی یو 2 رم 4 برنامه خیلی کرش میشه در ههر صورت ممنون از زحمتای شما فقط یوزر truecopy اجباریه؟ :))

**Comment by certifiedtruecopy** [comment]
سلام دوست  من چون روی برنامه برای نگرفتن خطا در بعضی قسمت ها استاپ گذاشتم تا برنامه در پس زمینه کار خودش رو بکنه شما فکر میکند کارش می‌کنه در واقع نرمال هست 

در رابطه با ساخت کاربر با نام TrueCopy  این هست که زمان جستجو فقط نام کاربرای رو نمایش بده که با این نام هستند در نسخه های قدیمی نام دیگر یوزر های سیستمی هم نمایش داده میشد در آپدیت اینده این که با چه نامی شروع شود رو انتخابی از طرف شما میکنم که خودتون انجام بدهید

**Comment by certifiedtruecopy** [comment]
در اپدیت جدید امروز مشکل رفتن سوالات زیر پنجره اصلی  برای ساخت کاربر حل شده است

**Comment by certifiedtruecopy** [comment]
در اپدیت امروز شما میتواند خودتون تصمیم بگیردید که کاربر با چه حرف خاصی ساخته بشه و زمان نمایش شما میکنید کدام گروه رو نمایش بده نه فقط با truecopy
