### ISSUE TITLE
Disable tabs and buttons if the connection is not established

### ISSUE THREAD

**Issue by alirezashojaei** [certifiedtruecopy/C2C_SSH#9]
I figured out that the tabs and buttons are working even if the ssh connection is not established. So it causes error. Since I'm not very good at tkinter, it would be cool if you work on that and disable tabs and buttons _if_ the connection _is not_ established

**Comment by certifiedtruecopy** [comment]
Thank you for your suggestion, I will definitely do this
And thanks for the tip about empty fields in user build time code
